name: "42Crunch API Conformance Scan"
description: "The API Conformance Scan action adds an automatic static Conformance Scan to your workflows"
inputs:
  api-token:
    description: "The API token to access 42Crunch Platform. Please create free account at https://platform.42crunch.com/register and follow hese steps to configure API_TOKEN https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm"
    required: false
  platform-url:
    description: "42Crunch platform URL"
    required: false
    default: "https://platform.42crunch.com"
  report-path:
    required: true
    description: "Path to JSON report from audit step"


branding:
  icon: "eye"
  color: "purple"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - python
    - cicd_python/runScan.py
    - --api-token
    - ${{ inputs.api-token }}
    - --platform-url
    - ${{ inputs.platform-url }}
    - --report-path
    - ${{ inputs.report-path }}